[project]
enable_telemetry = true

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 129600  # 1.5 days

# Enable third parties caching (e.g., LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

user_message_autoscroll = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

edit_message = true
prompt_playground = false
multi_modal = false

[UI]
name = "Fiddler Agentic Assistant"
default_theme = "light"
layout = "wide"

default_sidebar_state = "closed"

# Description of the assistant. This is used for HTML tags.
description = "Intelligent AI assistant powered by Fiddler's monitoring and observability platform"

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# The style of alert boxes. Can be "classic" or "modern".
alert_style = "modern"

# Custom login page image, relative to public directory or external URL
login_page_image = "/public/poweredby.jpg"

# Load assistant logo directly from URL.
logo_file_url = "/public/logo.png"

# Load assistant avatar image directly from URL.
default_avatar_file_url = "/public/logo.png"

# Specify optional one or more custom links in the header.
[[UI.header_links]]
    name = "Fiddler Monitoring"
    display_name = "Monitor in Fiddler"
    icon_url = "/public/logo.png"
    url = "https://preprod.cloud.fiddler.ai/"

[meta]
generated_by = "2.6.5"
