[project]
enable_telemetry = false

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 129600  # 1.5 days

# Enable third parties caching (e.g., LangChain cache)
cache = true

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

user_message_autoscroll = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

edit_message = true
prompt_playground = true
multi_modal = false

[UI]
name = "Fiddler AI Assistant"
default_theme = "light"
layout = "wide"

# default_sidebar_state = "open"

# Description of the assistant. This is used for HTML tags.
description = "Intelligent AI assistant powered by Fiddler's monitoring and observability platform"

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
custom_css = "/public/fiddler-theme.css"

# The style of alert boxes. Can be "classic" or "modern".
alert_style = "modern"

# Custom login page image, relative to public directory or external URL
login_page_image = "/public/poweredby.jpg"

# Custom login page image filter (Tailwind internal filters, no dark/light variants)
# login_page_image_filter = "brightness-50 grayscale"
# login_page_image_dark_filter = "contrast-200 blur-sm"

# Load assistant logo directly from URL.
logo_file_url = "/public/logo.png"

# Load assistant avatar image directly from URL.
default_avatar_file_url = "/public/logo.png"

# Specify optional one or more custom links in the header.
[[UI.header_links]]
    name = "Fiddler Gen AI Application Monitoring"
    display_name = "AI App Monitoring"
    icon_url = "https://avatars.githubusercontent.com/u/128686189?s=200&v=4"
    url = "https://demo.fiddler.ai/genai-applications/89ac25c1-8b36-4835-8cd6-60a7d0a1004d"

[meta]
generated_by = "2.6.5"
